name: Build and Deploy Customer micro to ECS

on:
  push:
    paths:
      - "microservices/customer/**"
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-to-ecr.yml
    with:
      microservice_name: "customer"
      microservice_path: "microservices/customer"
      ecr_image_name: ${{ vars.ECR_BACKEND_IMAGE }}
      ecs_cluster: ${{ vars.ECS_CLUSTER }}
      ecs_service: ${{ vars.ECS_BACKEND_SERVICE }}
      aws_region: ${{ vars.AWS_DEFAULT_REGION }}
      deploy_to_ecs: false  # Cambiar a true cuando quieras desplegar a ECS
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      GITREPO_TOKEN: ${{ secrets.GITREPO_TOKEN }}
